version: "3.3"
services:
  flask-app:
    restart: always
    build:
      context: .
    ports:
      - "5000:5000"
    network_mode: "host"
    restart: always
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
